/* Generated by JTB 1.4.4 */
package main.java.visitor;

import main.java.syntaxtree.*;

public interface IVoidVisitor {

  void visit(final NodeList n);

  void visit(final NodeListOptional n);

  void visit(final NodeOptional n);

  void visit(final NodeSequence n);

  void visit(final NodeToken n);

  void visit(final Goal n);

  void visit(final StmtList n);

  void visit(final Procedure n);

  void visit(final Stmt n);

  void visit(final NoOpStmt n);

  void visit(final ErrorStmt n);

  void visit(final CJumpStmt n);

  void visit(final JumpStmt n);

  void visit(final HStoreStmt n);

  void visit(final HLoadStmt n);

  void visit(final MoveStmt n);

  void visit(final PrintStmt n);

  void visit(final Exp n);

  void visit(final StmtExp n);

  void visit(final Call n);

  void visit(final HAllocate n);

  void visit(final BinOp n);

  void visit(final Operator n);

  void visit(final SimpleExp n);

  void visit(final Temp n);

  void visit(final IntegerLiteral n);

  void visit(final Label n);

}
