/* Generated by JTB 1.4.4 */
package main.java.syntaxtree;

import main.java.visitor.IRetArguVisitor;
import main.java.visitor.IRetVisitor;
import main.java.visitor.IVoidArguVisitor;
import main.java.visitor.IVoidVisitor;

public class HAllocate implements INode {

    private static final long serialVersionUID = 144L;
    public NodeToken f0;
    public SimpleExp f1;

    public HAllocate(final NodeToken n0, final SimpleExp n1) {
        f0 = n0;
        f1 = n1;
    }

    public HAllocate(final SimpleExp n0) {
        f0 = new NodeToken("HALLOCATE");
        f1 = n0;
    }

    public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
        return vis.visit(this, argu);
    }

    public <R> R accept(final IRetVisitor<R> vis) {
        return vis.visit(this);
    }

    public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
        vis.visit(this, argu);
    }

    public void accept(final IVoidVisitor vis) {
        vis.visit(this);
    }

}
