/* Generated by JTB 1.4.4 */
package main.java.syntaxtree;

import main.java.visitor.IRetArguVisitor;
import main.java.visitor.IRetVisitor;
import main.java.visitor.IVoidArguVisitor;
import main.java.visitor.IVoidVisitor;

public interface INodeList extends INode {

    void addNode(final INode n);

    INode elementAt(int i);

    java.util.Iterator<INode> elements();

    int size();

    <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu);

    <R> R accept(final IRetVisitor<R> vis);

    <A> void accept(final IVoidArguVisitor<A> vis, final A argu);

    void accept(final IVoidVisitor vis);

}
