/* Generated by JTB 1.4.4 */
package syntaxtree;

import visitor.IRetArguVisitor;
import visitor.IRetVisitor;
import visitor.IVoidArguVisitor;
import visitor.IVoidVisitor;

public class CJumpStmt implements INode {

  public NodeToken f0;

  public Temp f1;

  public Label f2;

  private static final long serialVersionUID = 144L;

  public CJumpStmt(final NodeToken n0, final Temp n1, final Label n2) {
    f0 = n0;
    f1 = n1;
    f2 = n2;
  }

  public CJumpStmt(final Temp n0, final Label n1) {
    f0 = new NodeToken("CJUMP");
    f1 = n0;
    f2 = n1;
  }

  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }

  public <R> R accept(final IRetVisitor<R> vis) {
    return vis.visit(this);
  }

  public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
    vis.visit(this, argu);
  }

  public void accept(final IVoidVisitor vis) {
    vis.visit(this);
  }

}
