/* Generated by JTB 1.4.4 */
package syntaxtree;

import visitor.*;

public class HStoreStmt implements INode {

  public NodeToken f0;

  public Temp f1;

  public IntegerLiteral f2;

  public Temp f3;

  private static final long serialVersionUID = 144L;

  public HStoreStmt(final NodeToken n0, final Temp n1, final IntegerLiteral n2, final Temp n3) {
    f0 = n0;
    f1 = n1;
    f2 = n2;
    f3 = n3;
  }

  public HStoreStmt(final Temp n0, final IntegerLiteral n1, final Temp n2) {
    f0 = new NodeToken("HSTORE");
    f1 = n0;
    f2 = n1;
    f3 = n2;
  }

  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }

  public <R> R accept(final IRetVisitor<R> vis) {
    return vis.visit(this);
  }

  public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
    vis.visit(this, argu);
  }

  public void accept(final IVoidVisitor vis) {
    vis.visit(this);
  }

}
