/* Generated by JTB 1.4.4 */
package syntaxtree;

import visitor.IRetArguVisitor;
import visitor.IRetVisitor;
import visitor.IVoidArguVisitor;
import visitor.IVoidVisitor;

public interface INodeList extends INode {

  void addNode(final INode n);

  INode elementAt(int i);

  java.util.Iterator<INode> elements();

  int size();

  <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu);

  <R> R accept(final IRetVisitor<R> vis);

  <A> void accept(final IVoidArguVisitor<A> vis, final A argu);

  void accept(final IVoidVisitor vis);

}
