/* Generated by JTB 1.4.4 */
package syntaxtree;

import visitor.IRetArguVisitor;
import visitor.IRetVisitor;
import visitor.IVoidArguVisitor;
import visitor.IVoidVisitor;

public class Procedure implements INode {

  public Label f0;

  public NodeToken f1;

  public IntegerLiteral f2;

  public NodeToken f3;

  public StmtExp f4;

  private static final long serialVersionUID = 144L;

  public Procedure(final Label n0, final NodeToken n1, final IntegerLiteral n2, final NodeToken n3, final StmtExp n4) {
    f0 = n0;
    f1 = n1;
    f2 = n2;
    f3 = n3;
    f4 = n4;
  }

  public Procedure(final Label n0, final IntegerLiteral n1, final StmtExp n2) {
    f0 = n0;
    f1 = new NodeToken("[");
    f2 = n1;
    f3 = new NodeToken("]");
    f4 = n2;
  }

  public <R, A> R accept(final IRetArguVisitor<R, A> vis, final A argu) {
    return vis.visit(this, argu);
  }

  public <R> R accept(final IRetVisitor<R> vis) {
    return vis.visit(this);
  }

  public <A> void accept(final IVoidArguVisitor<A> vis, final A argu) {
    vis.visit(this, argu);
  }

  public void accept(final IVoidVisitor vis) {
    vis.visit(this);
  }

}
