/* Generated by JTB 1.4.4 */
package visitor;

import syntaxtree.*;

public interface IRetVisitor<R> {

  public R visit(final NodeList n);

  public R visit(final NodeListOptional n);

  public R visit(final NodeOptional n);

  public R visit(final NodeSequence n);

  public R visit(final NodeToken n);

  public R visit(final Goal n);

  public R visit(final StmtList n);

  public R visit(final Procedure n);

  public R visit(final Stmt n);

  public R visit(final NoOpStmt n);

  public R visit(final ErrorStmt n);

  public R visit(final CJumpStmt n);

  public R visit(final JumpStmt n);

  public R visit(final HStoreStmt n);

  public R visit(final HLoadStmt n);

  public R visit(final MoveStmt n);

  public R visit(final PrintStmt n);

  public R visit(final Exp n);

  public R visit(final StmtExp n);

  public R visit(final Call n);

  public R visit(final HAllocate n);

  public R visit(final BinOp n);

  public R visit(final Operator n);

  public R visit(final SimpleExp n);

  public R visit(final Temp n);

  public R visit(final IntegerLiteral n);

  public R visit(final Label n);

}
